// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HUUkFRFeFmsCfYa16gLFflENHqYWXL8',
    appId: '1:90416730355:web:565d903f16a74a7436e786',
    messagingSenderId: '90416730355',
    projectId: 'smart-saver-wallet-ver12-ad',
    authDomain: 'smart-saver-wallet-ver12-ad.firebaseapp.com',
    storageBucket: 'smart-saver-wallet-ver12-ad.firebasestorage.app',
    measurementId: 'G-PBR0PSLTLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvTtYlMqQe08OtZwSqDHaZFYa0fC1Ne9w',
    appId: '1:90416730355:android:6a27146de4d028ce36e786',
    messagingSenderId: '90416730355',
    projectId: 'smart-saver-wallet-ver12-ad',
    storageBucket: 'smart-saver-wallet-ver12-ad.firebasestorage.app',
  );
}
